import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { WalletWrapper } from "@/components/WalletWrapper";
import Navbar from "@/components/Navbar";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Superteam Workshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <WalletWrapper>
          <Navbar />
          {children}
        </WalletWrapper>
      </body>
    </html>
  );
}
